[package]
name = "tnf_server"
version = "0.1.0"
authors = ["qthree <qthree3@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
winapi = { version = "0.3.6", features = ["consoleapi"] }
tnf_common = { path = "../common" }

[lib]
crate-type = ["cdylib"]
